### ISSUE TITLE
Builder not found in RAML import

### ISSUE THREAD

**Issue by thesourcerer8** [SmartBear/soapui-raml-plugin#27]
I am trying to import the RAML specification from https://factory.macrofab.com/apidoc/v2/raml.zip

**Comment by thesourcerer8** [comment]
I am using ReadyAPI 2.4.0

**Comment by Alexander-Paeshin** [comment]
What version of the plugin are you using?

**Comment by thesourcerer8** [comment]
Version 1.3.2

**Comment by Alexander-Paeshin** [comment]
Ok, thanks.
Please, create a support request
https://support.smartbear.com/message/?prod=ReadyAPI

**Comment by thesourcerer8** [comment]
That's what I did, and the SmartBear support told me to file an issue here, since they do not support the RAML plugin.

**Comment by Alexander-Paeshin** [comment]
I've investigated your RAML definition and found that it is incorrect. According to RAML 0.8 specification (https://github.com/raml-org/raml-spec/blob/master/versions/raml-08/raml-08.md) the method property can contains only the following properties: description, headers, protocols, queryParameters, body and responses. But the displayName property is specified for some methods,  which is not allowed.

**Comment by thesourcerer8** [comment]
Thanks a lot for the investigation!

**Comment by thesourcerer8** [comment]
The problem has been fixed, MacroFab are providing correct RAML files now. Thanks!
