### ISSUE TITLE
BaseUriParameters not working

### ISSUE THREAD

**Issue by PascalBru** [SmartBear/soapui-raml-plugin#7]
In my RAML-File i have the following lines:

baseUri: https://{hostName}.test-domain.de/wifiBase/{version}
baseUriParameters:
  hostName:
    enum: ["api", "api-dev"]

the import of the file is working, however in the SoapUI i get every ResourcePath with an ending {hostName}

Could you please have a look at that.

Regards
Pascal

**Comment by lrevnic** [comment]
Hello,

Was this finally fixed? I think we have a similar issue with latest soapUi plugin for RAML.

Thank you,
Lucian

**Comment by olensmar** [comment]
Hi Lucian

if you mean template parameters in hostname I'm not sure - please feel free to open an issue on https://github.com/smartbear/soapui

/Ole
